//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentsManger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int IDDescription { get; set; }
        public string Floor { get; set; }
        public string LivingSpace { get; set; }
        public string NumberOfRooms { get; set; }
        public string ApartmentType { get; set; }
        public string EnergyClass { get; set; }
        public string ApartmentIDApartment { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
